# Generated by Django 5.0.3 on 2026-03-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("ip_address_or_url", models.CharField(max_length=255)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("SERVER", "Server"),
                            ("ROUTER", "Router"),
                            ("API", "API"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("PING", "Ping (ICMP)"),
                            ("TCP", "TCP Port"),
                            ("HTTP_GET", "HTTP GET"),
                        ],
                        max_length=20,
                    ),
                ),
                ("check_port", models.PositiveIntegerField(blank=True, null=True)),
                ("check_interval_minutes", models.PositiveIntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "assets",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssetStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UP", "Up"),
                            ("DOWN", "Down"),
                            ("DEGRADED", "Degraded"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "asset_status_logs",
                "ordering": ["-checked_at"],
            },
        ),
    ]
