# Generated by Django 5.0.3 on 2026-03-09 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("STATUS_CHANGE", "Status Change"),
                            ("COMMENT", "Comment"),
                            ("ASSIGNMENT", "Assignment"),
                            ("SYSTEM_NOTE", "System Note"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_value", models.CharField(blank=True, max_length=50)),
                ("new_value", models.CharField(blank=True, max_length=50)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "incident_logs",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SLAPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("resolution_hours", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "sla_policies",
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="NEW",
                        max_length=15,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("SYSTEM", "System"), ("MANUAL", "Manual")],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                ("sla_deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "db_table": "incidents",
                "ordering": ["-created_at"],
            },
        ),
    ]
