# Generated by Django 5.0.3 on 2026-04-02 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0002_initial"),
        ("users", "0004_user_role_nonnull"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusRoleMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        max_length=15,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_mappings",
                        to="users.role",
                    ),
                ),
            ],
            options={
                "db_table": "status_role_mappings",
                "ordering": ["status"],
            },
        ),
    ]
