# Generated by Django 5.0.3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codename", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "app_permissions",
                "ordering": ["codename"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False, help_text="Bypass all permission checks."
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="System roles cannot be deleted via the API.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="users.apppermission"
                    ),
                ),
            ],
            options={
                "db_table": "roles",
                "ordering": ["name"],
            },
        ),
        # Add a NEW nullable FK column (role_fk) — keep old CharField role intact
        migrations.AddField(
            model_name="user",
            name="role_fk",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.role",
            ),
        ),
    ]
